spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?characterEncoding=UTF-8&useUnicode=true
spring.datasource.username=mbc
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=goldentime

server.port=1111

spring.datasource.hikari.connection-init-sql=SET client_encoding TO 'UTF8'
